QR_CREATED = "QR_CREATED"

RECEIVED = "RECEIVED"

ALLOCATED = "ALLOCATED"

PRINT_STARTED = "PRINT_STARTED"

PRINT_COMPLETED = "PRINT_COMPLETED"

PACKAGED = "PACKAGED"

DISPATCHED = "DISPATCHED"

DELIVERED = "DELIVERED"

EXECUTION_STARTED = "EXECUTION_STARTED"

EXECUTION_COMPLETED = "EXECUTION_COMPLETED"

ROLL_CLOSED = "ROLL_CLOSED"
