"""initial schema

Revision ID: 1291862fdcf0
Revises: 
Create Date: 2026-08-31 16:04:28.256322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1291862fdcf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('activity', sa.String(length=300), nullable=False),
    sa.Column('performed_by', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_module'), 'activity_logs', ['module'], unique=False)
    op.create_index(op.f('ix_activity_logs_reference'), 'activity_logs', ['reference'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_code', sa.String(length=30), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=False),
    sa.Column('agency_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=False),
    sa.Column('campaign_name', sa.String(length=250), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANNING', 'IMPORTED', 'ARTWORK_PENDING', 'READY_FOR_PRODUCTION', 'PRINTING', 'PACKAGING', 'DISPATCHED', 'EXECUTING', 'COMPLETED', 'CANCELLED', name='campaignstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_code'), 'campaigns', ['campaign_code'], unique=True)
    op.create_index(op.f('ix_campaigns_client_name'), 'campaigns', ['client_name'], unique=False)
    op.create_index(op.f('ix_campaigns_uuid'), 'campaigns', ['uuid'], unique=True)
    op.create_table('clients',
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_sequences_document_type'), 'document_sequences', ['document_type'], unique=True)
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_code', sa.String(length=20), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer_name')
    )
    op.create_index(op.f('ix_manufacturers_manufacturer_code'), 'manufacturers', ['manufacturer_code'], unique=True)
    op.create_index(op.f('ix_manufacturers_uuid'), 'manufacturers', ['uuid'], unique=True)
    op.create_table('printers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printer_code', sa.String(length=20), nullable=False),
    sa.Column('printer_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('print_capacity_day', sa.Float(), nullable=False),
    sa.Column('night_shift_capacity', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('printer_name')
    )
    op.create_index(op.f('ix_printers_printer_code'), 'printers', ['printer_code'], unique=True)
    op.create_index(op.f('ix_printers_uuid'), 'printers', ['uuid'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=20), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_index(op.f('ix_suppliers_supplier_name'), 'suppliers', ['supplier_name'], unique=False)
    op.create_index(op.f('ix_suppliers_uuid'), 'suppliers', ['uuid'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=20), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_uuid'), 'warehouses', ['uuid'], unique=True)
    op.create_index(op.f('ix_warehouses_warehouse_code'), 'warehouses', ['warehouse_code'], unique=True)
    op.create_table('campaign_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('planned_sqft', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(length=20), nullable=False),
    sa.Column('import_batch', sa.String(length=40), nullable=False),
    sa.Column('total_locations', sa.Integer(), nullable=False),
    sa.Column('total_walls', sa.Integer(), nullable=False),
    sa.Column('total_sqft', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_versions_import_batch'), 'campaign_versions', ['import_batch'], unique=True)
    op.create_table('media_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=False),
    sa.Column('gsm', sa.Float(), nullable=True),
    sa.Column('finish', sa.String(length=100), nullable=True),
    sa.Column('standard_length_m', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_products_product_code'), 'media_products', ['product_code'], unique=True)
    op.create_index(op.f('ix_media_products_uuid'), 'media_products', ['uuid'], unique=True)
    op.create_table('production_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=30), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_batches_batch_number'), 'production_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_production_batches_printer_id'), 'production_batches', ['printer_id'], unique=False)
    op.create_index(op.f('ix_production_batches_uuid'), 'production_batches', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_printer_id'), 'users', ['printer_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('campaign_artworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_version_id', sa.Integer(), nullable=False),
    sa.Column('artwork_code', sa.String(length=40), nullable=False),
    sa.Column('artwork_name', sa.String(length=250), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=False),
    sa.Column('height_ft', sa.Float(), nullable=False),
    sa.Column('artwork_sqft', sa.Float(), nullable=False),
    sa.Column('assigned_walls', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_version_id'], ['campaign_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_artworks_artwork_code'), 'campaign_artworks', ['artwork_code'], unique=True)
    op.create_index(op.f('ix_campaign_artworks_campaign_version_id'), 'campaign_artworks', ['campaign_version_id'], unique=False)
    op.create_index(op.f('ix_campaign_artworks_uuid'), 'campaign_artworks', ['uuid'], unique=True)
    op.create_table('campaign_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_version_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('imported_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_version_id'], ['campaign_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_import_logs_campaign_version_id'), 'campaign_import_logs', ['campaign_version_id'], unique=False)
    op.create_table('campaign_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_version_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('town', sa.String(length=150), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('wall_width_ft', sa.Float(), nullable=False),
    sa.Column('wall_height_ft', sa.Float(), nullable=False),
    sa.Column('wall_sqft', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_sqft', sa.Float(), nullable=False),
    sa.Column('wall_type', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_version_id'], ['campaign_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_locations_campaign_version_id'), 'campaign_locations', ['campaign_version_id'], unique=False)
    op.create_index(op.f('ix_campaign_locations_district'), 'campaign_locations', ['district'], unique=False)
    op.create_index(op.f('ix_campaign_locations_state'), 'campaign_locations', ['state'], unique=False)
    op.create_table('media_rolls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=30), nullable=False),
    sa.Column('roll_number', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_roll_no', sa.String(length=150), nullable=True),
    sa.Column('purchase_order', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('ordered_length_m', sa.Float(), nullable=False),
    sa.Column('actual_length_m', sa.Float(), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=False),
    sa.Column('total_sqft', sa.Float(), nullable=False),
    sa.Column('available_sqft', sa.Float(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('qr_payload', sa.String(length=255), nullable=True),
    sa.Column('qr_image_path', sa.String(length=500), nullable=True),
    sa.Column('qr_generated_on', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['media_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_rolls_asset_id'), 'media_rolls', ['asset_id'], unique=True)
    op.create_index(op.f('ix_media_rolls_roll_number'), 'media_rolls', ['roll_number'], unique=True)
    op.create_index(op.f('ix_media_rolls_uuid'), 'media_rolls', ['uuid'], unique=True)
    op.create_table('printing_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=False),
    sa.Column('printer_id', sa.Integer(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=150), nullable=True),
    sa.Column('shift', sa.String(length=30), nullable=False),
    sa.Column('planned_sqft', sa.Float(), nullable=False),
    sa.Column('printed_sqft', sa.Float(), nullable=False),
    sa.Column('wastage_sqft', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printing_sessions_printer_id'), 'printing_sessions', ['printer_id'], unique=False)
    op.create_index(op.f('ix_printing_sessions_production_batch_id'), 'printing_sessions', ['production_batch_id'], unique=False)
    op.create_index(op.f('ix_printing_sessions_uuid'), 'printing_sessions', ['uuid'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_uuid'), 'user_sessions', ['uuid'], unique=True)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_roll_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('reference_module', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('wastage_sqft', sa.Float(), nullable=False),
    sa.Column('qty_in', sa.Float(), nullable=False),
    sa.Column('qty_out', sa.Float(), nullable=False),
    sa.Column('balance_qty', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=150), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['media_roll_id'], ['media_rolls.id'], ),
    sa.ForeignKeyConstraint(['printer_id'], ['printers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_campaign_id'), 'inventory_transactions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_media_roll_id'), 'inventory_transactions', ['media_roll_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_printer_id'), 'inventory_transactions', ['printer_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_warehouse_id'), 'inventory_transactions', ['warehouse_id'], unique=False)
    op.create_table('media_roll_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_roll_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('current_status', sa.String(length=40), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('scanned_by', sa.String(length=100), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_roll_id'], ['media_rolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_roll_history_media_roll_id'), 'media_roll_history', ['media_roll_id'], unique=False)
    op.create_index(op.f('ix_media_roll_history_uuid'), 'media_roll_history', ['uuid'], unique=True)
    op.create_table('print_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('printing_session_id', sa.Integer(), nullable=True),
    sa.Column('tile_no', sa.Integer(), nullable=True),
    sa.Column('artwork_code', sa.String(length=100), nullable=True),
    sa.Column('width_ft', sa.Float(), nullable=True),
    sa.Column('height_ft', sa.Float(), nullable=True),
    sa.Column('bleed_left_in', sa.Float(), nullable=True),
    sa.Column('bleed_right_in', sa.Float(), nullable=True),
    sa.Column('printed_sqft', sa.Float(), nullable=True),
    sa.Column('trimmed_sqft', sa.Float(), nullable=True),
    sa.Column('waste_sqft', sa.Float(), nullable=True),
    sa.Column('package_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['printing_session_id'], ['printing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=False),
    sa.Column('campaign_artwork_id', sa.Integer(), nullable=False),
    sa.Column('planned_sqft', sa.Float(), nullable=False),
    sa.Column('printed_sqft', sa.Float(), nullable=False),
    sa.Column('wastage_sqft', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_artwork_id'], ['campaign_artworks.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_items_uuid'), 'production_items', ['uuid'], unique=True)
    op.create_table('roll_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_roll_id', sa.Integer(), nullable=False),
    sa.Column('measured_length_ft', sa.Float(), nullable=False),
    sa.Column('measured_width_ft', sa.Float(), nullable=False),
    sa.Column('actual_sqft', sa.Float(), nullable=False),
    sa.Column('measured_by', sa.String(length=150), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_roll_id'], ['media_rolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roll_measurements_media_roll_id'), 'roll_measurements', ['media_roll_id'], unique=False)
    op.create_table('wastage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_roll_id', sa.Integer(), nullable=True),
    sa.Column('printing_session_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=150), nullable=True),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_roll_id'], ['media_rolls.id'], ),
    sa.ForeignKeyConstraint(['printing_session_id'], ['printing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_item_id', sa.Integer(), nullable=False),
    sa.Column('campaign_artwork_id', sa.Integer(), nullable=False),
    sa.Column('production_batch_id', sa.Integer(), nullable=False),
    sa.Column('media_roll_id', sa.Integer(), nullable=False),
    sa.Column('allocated_sqft', sa.Float(), nullable=False),
    sa.Column('printed_sqft', sa.Float(), nullable=False),
    sa.Column('wastage_sqft', sa.Float(), nullable=False),
    sa.Column('balance_sqft', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_artwork_id'], ['campaign_artworks.id'], ),
    sa.ForeignKeyConstraint(['media_roll_id'], ['media_rolls.id'], ),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['production_item_id'], ['production_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_allocations_campaign_artwork_id'), 'production_allocations', ['campaign_artwork_id'], unique=False)
    op.create_index(op.f('ix_production_allocations_media_roll_id'), 'production_allocations', ['media_roll_id'], unique=False)
    op.create_index(op.f('ix_production_allocations_production_batch_id'), 'production_allocations', ['production_batch_id'], unique=False)
    op.create_index(op.f('ix_production_allocations_production_item_id'), 'production_allocations', ['production_item_id'], unique=False)
    op.create_index(op.f('ix_production_allocations_status'), 'production_allocations', ['status'], unique=False)
    op.create_index(op.f('ix_production_allocations_uuid'), 'production_allocations', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_allocations_uuid'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_status'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_production_item_id'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_production_batch_id'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_media_roll_id'), table_name='production_allocations')
    op.drop_index(op.f('ix_production_allocations_campaign_artwork_id'), table_name='production_allocations')
    op.drop_table('production_allocations')
    op.drop_table('wastage')
    op.drop_index(op.f('ix_roll_measurements_media_roll_id'), table_name='roll_measurements')
    op.drop_table('roll_measurements')
    op.drop_index(op.f('ix_production_items_uuid'), table_name='production_items')
    op.drop_table('production_items')
    op.drop_table('print_tiles')
    op.drop_index(op.f('ix_media_roll_history_uuid'), table_name='media_roll_history')
    op.drop_index(op.f('ix_media_roll_history_media_roll_id'), table_name='media_roll_history')
    op.drop_table('media_roll_history')
    op.drop_index(op.f('ix_inventory_transactions_warehouse_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_printer_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_media_roll_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_campaign_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_user_sessions_uuid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_printing_sessions_uuid'), table_name='printing_sessions')
    op.drop_index(op.f('ix_printing_sessions_production_batch_id'), table_name='printing_sessions')
    op.drop_index(op.f('ix_printing_sessions_printer_id'), table_name='printing_sessions')
    op.drop_table('printing_sessions')
    op.drop_index(op.f('ix_media_rolls_uuid'), table_name='media_rolls')
    op.drop_index(op.f('ix_media_rolls_roll_number'), table_name='media_rolls')
    op.drop_index(op.f('ix_media_rolls_asset_id'), table_name='media_rolls')
    op.drop_table('media_rolls')
    op.drop_index(op.f('ix_campaign_locations_state'), table_name='campaign_locations')
    op.drop_index(op.f('ix_campaign_locations_district'), table_name='campaign_locations')
    op.drop_index(op.f('ix_campaign_locations_campaign_version_id'), table_name='campaign_locations')
    op.drop_table('campaign_locations')
    op.drop_index(op.f('ix_campaign_import_logs_campaign_version_id'), table_name='campaign_import_logs')
    op.drop_table('campaign_import_logs')
    op.drop_index(op.f('ix_campaign_artworks_uuid'), table_name='campaign_artworks')
    op.drop_index(op.f('ix_campaign_artworks_campaign_version_id'), table_name='campaign_artworks')
    op.drop_index(op.f('ix_campaign_artworks_artwork_code'), table_name='campaign_artworks')
    op.drop_table('campaign_artworks')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_printer_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_production_batches_uuid'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_printer_id'), table_name='production_batches')
    op.drop_index(op.f('ix_production_batches_batch_number'), table_name='production_batches')
    op.drop_table('production_batches')
    op.drop_index(op.f('ix_media_products_uuid'), table_name='media_products')
    op.drop_index(op.f('ix_media_products_product_code'), table_name='media_products')
    op.drop_table('media_products')
    op.drop_index(op.f('ix_campaign_versions_import_batch'), table_name='campaign_versions')
    op.drop_table('campaign_versions')
    op.drop_table('campaign_cities')
    op.drop_index(op.f('ix_warehouses_warehouse_code'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_uuid'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_suppliers_uuid'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_supplier_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_printers_uuid'), table_name='printers')
    op.drop_index(op.f('ix_printers_printer_code'), table_name='printers')
    op.drop_table('printers')
    op.drop_index(op.f('ix_manufacturers_uuid'), table_name='manufacturers')
    op.drop_index(op.f('ix_manufacturers_manufacturer_code'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_document_sequences_document_type'), table_name='document_sequences')
    op.drop_table('document_sequences')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_code'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_campaigns_uuid'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_client_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_code'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_activity_logs_reference'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_module'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
